#!/usr/bin/env bash
# set -x
script="../bin/glue-validator"
output="$(mktemp)"
failed=0
export PYTHONPATH="../:../lib"

function test_ldif {
	echo -n "Testing ${ldif} ... "
	if ! ${script} -v 3 -f "$1" >"${output}" 2>"${output}.err"; then
		echo "FAIL" 1>&2
		cat "${output}"
		cat "${output}.err"
		failed=1
		return
	fi
	# if [ $(wc -l ${output} | sed 's/ .*//') -ne 2 ]; then
	#   echo "FAIL" 1>&2
	#   cat ${output}
	#   cat ${output}.err
	#   return
	# fi
        if [ -s "${output}.err" ]; then
		echo "FAIL" 1>&2
		cat "${output}.err"
		failed=1
		return
	fi
	echo "OK"
}

ldif="ldif/GLUE2AdminDomain/AdminDomain.ldif"
test_ldif "${ldif}"

ldif="ldif/GLUE2Location/Location.ldif"
test_ldif "${ldif}"

ldif="ldif/GLUE2Contact/Contact.ldif"
test_ldif "${ldif}"

rm -f "${output}"
rm -f "${output}.err"

if [ "$failed" = "1" ]; then
	echo "Error when running the tests"
	exit 1
fi
