---
name: Create packages and test installation

on:
  pull_request:

jobs:
  # XXX done outside of the matrix due to different container name
  build-centos7:
    name: Build CentOS 7 RPMs
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils rpmlint
          yum-builddep -y glue-validator.spec
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.el7.noarch.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms7
          path: |
            build/RPMS/noarch/glue-validator-*-1.el7.noarch.rpm
  install-centos7:
    name: Install CentOS 7 RPMs
    needs: build-centos7
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms7
      - name: Install generated RPMs
        run: |
          yum localinstall -y glue-validator-*.el7.noarch.rpm
      - name: Test installed RPMs
        run: |
          curl https://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo > /etc/yum.repos.d/EGI-trustanchors.repo
          yum install -y ca-policy-egi-core
          echo 'capath = /etc/grid-security/certificates' >> /etc/glite/glue-validator.conf
          glue-validator -v -c /etc/glite/glue-validator.conf

  # Use a matrix for AlmaLinux versions
  build:
    strategy:
      matrix:
        almalinux-version: [8, 9]
    name: Build AlmaLinux ${{ matrix.almalinux-version }} RPMs
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build yum-utils rpmlint
          yum-builddep -y glue-validator.spec
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.el${{ matrix.almalinux-version }}.noarch.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms${{ matrix.almalinux-version }}
          path: |
            build/RPMS/noarch/glue-validator-*-1.el${{ matrix.almalinux-version }}.noarch.rpm
  install:
    strategy:
      matrix:
        almalinux-version: [8, 9]
    name: Install AlmaLinux ${{ matrix.almalinux-version }} RPMs
    needs: build
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms${{ matrix.almalinux-version }}
      - name: Install generated RPMs
        run: |
          yum localinstall -y glue-validator-*.el${{ matrix.almalinux-version }}.noarch.rpm
